google.maps.__gjsload__('infowindow', function(_){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var nya=function(a){if(a.Rb&&"function"==typeof a.Rb)a=a.Rb();else if(_.Ka(a)||"string"===typeof a)a=a.length;else{var b=0,c;for(c in a)b++;a=b}return a},oya=function(a,b){if("function"==typeof a.every)return a.every(b,void 0);if(_.Ka(a)||"string"===typeof a)return Array.prototype.every.call(a,b,void 0);for(var c=_.Wl(a),d=_.Vl(a),e=d.length,f=0;f<e;f++)if(!b.call(void 0,d[f],c&&c[f],a))return!1;return!0},XE=function(a){this.g=new _.aB;this.size=0;if(a){a=_.Vl(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c]);
this.size=this.g.size}},YE=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+_.Na(a):b.substr(0,1)+a},pya=function(a,b){var c=nya(b);if(a.Rb()>c)return!1;!(b instanceof XE)&&5<c&&(b=new XE(b));return oya(a,function(d){var e=b;return e.contains&&"function"==typeof e.contains?e.contains(d):e.Lh&&"function"==typeof e.Lh?e.Lh(d):_.Ka(e)||"string"===typeof e?_.hb(e,d):_.qla(e,d)})},qya=function(){this.g=new XE},rya=function(a,b){if(1==a.g.size){var c=_.u(Array,"from").call(Array,_.u(a.g,
"values").call(a.g))[0];c.dk!=b.dk&&(c.set("map",null),a.g.delete(c))}a.g.add(b)},$E=function(a){var b=this;this.K=a.Vu;this.l=null;this.L=a.shouldFocus;this.g=_.pm("div");_.Kt(this.g,"default");this.g.style.position="absolute";this.g.style.left=this.g.style.top="0";a.sh.floatPane.appendChild(this.g);this.C=_.pm("div",this.g);this.o=_.pm("div",this.C);this.h=_.pm("div",this.o);this.h.setAttribute("role","dialog");this.h.tabIndex=-1;this.i=_.pm("div",this.h);_.wra(this.g);_.Nl(this.h,"gm-style-iw");
_.Nl(this.C,"gm-style-iw-a");_.Nl(this.o,"gm-style-iw-t");_.Nl(this.h,"gm-style-iw-c");_.Nl(this.i,"gm-style-iw-d");_.qi.g&&(a.lc?this.h.style.paddingLeft=0:this.h.style.paddingRight=0,this.h.style.paddingBottom=0,this.i.style.overflow="scroll");ZE(this,!1);_.L.addDomListener(this.g,"mousedown",_.Af);_.L.addDomListener(this.g,"mouseup",_.Af);_.L.addDomListener(this.g,"mousemove",_.Af);_.L.addDomListener(this.g,"pointerdown",_.Af);_.L.addDomListener(this.g,"pointerup",_.Af);_.L.addDomListener(this.g,
"pointermove",_.Af);_.L.addDomListener(this.g,"dblclick",_.Af);_.L.addDomListener(this.g,"click",_.Af);_.L.addDomListener(this.g,"touchstart",_.Af);_.L.addDomListener(this.g,"touchend",_.Af);_.L.addDomListener(this.g,"touchmove",_.Af);_.L.Jb(this.g,"contextmenu",this,this.Zw);_.L.Jb(this.g,"wheel",this,_.Af);_.L.Jb(this.g,"mousewheel",this,_.xf);_.L.Jb(this.g,"MozMousePixelScroll",this,_.xf);this.F=new _.rA({Vh:new _.N(8,8),Dg:new _.sg(14,14),offset:new _.N(-6,-6)});this.h.appendChild(this.F.element);
_.L.addDomListener(this.F.element,"click",function(c){_.Af(c);_.L.trigger(b,"closeclick");b.set("open",!1)});this.j=null;this.G=!1;this.m=new _.bi(function(){!b.G&&b.get("content")&&b.get("visible")&&(_.L.trigger(b,"domready"),b.G=!0)},0);this.J=_.L.addDomListener(this.g,"keydown",function(c){"Escape"!==c.key&&"Esc"!==c.key||!b.h.contains(document.activeElement)||(c.stopPropagation(),_.L.trigger(b,"closeclick"),b.set("open",!1))})},sya=function(a){var b=!!a.get("open"),c=a.get("content");c=b?c:null;
if(c==a.j)ZE(a,b&&a.get("position"));else{if(a.j){var d=a.j.parentNode;d==a.i&&d.removeChild(a.j)}c&&(a.G=!1,a.i.appendChild(c));ZE(a,b&&a.get("position"));a.j=c;aF(a)}},tya=function(a){var b=a.get("pixelOffset")||new _.sg(0,0),c=new _.sg(a.h.offsetWidth,a.h.offsetHeight);a=-b.height+c.height+11+60;var d=b.height+60,e=-b.width+c.width/2+60;c=b.width+c.width/2+60;0>b.height&&(d-=b.height);return{top:a,bottom:d,left:e,right:c}},ZE=function(a,b){a.g.style.visibility=b?"":"hidden";b&&a.L&&(a.focus(),
a.L=!1)},aF=function(a){var b=a.get("layoutPixelBounds"),c=a.get("pixelOffset");var d=a.get("maxWidth")||648;var e=a.get("minWidth")||0;c?(b?(c=b.Ba-b.va-(11+-c.height),b=b.Ga-b.ya-6,240<=b&&(b-=120),240<=c&&(c-=120)):(b=648,c=654),b=Math.min(b,d),b=Math.max(e,b),b=Math.max(0,b),c=Math.max(0,c),d={Ue:new _.sg(b,c),minWidth:e}):d=null;if(e=d)d=e.Ue,e=e.minWidth,a.h.style.maxWidth=_.vl(d.width),a.h.style.maxHeight=_.vl(d.height),a.h.style.minWidth=_.vl(e),a.i.style.maxHeight=_.qi.g?_.vl(d.height-18):
_.vl(d.height-36),bF(a),a.m.start()},bF=function(a){var b=a.get("position");if(b&&a.get("pixelOffset")){var c=tya(a),d=b.x-c.left,e=b.y-c.top,f=b.x+c.right;c=b.y+c.bottom;_.om(a.C,b);b=a.get("zIndex");_.qm(a.g,_.Ne(b)?b:e+60);a.set("pixelBounds",_.Ch(d,e,f,c))}},uya=function(a,b){var c=a.__gm;a=c.get("panes");c=c.get("innerContainer");b={sh:a,lc:_.lr.lc(),Vu:c,shouldFocus:b};return new $E(b)},cF=function(a,b,c){var d=this;this.l=!0;this.Pa=this.j=this.i=null;var e=b.__gm,f=b instanceof _.Kf;f&&c?
c.then(function(m){d.l&&(d.i=m,d.Pa=new _.sA(function(p){d.j=new _.cn(b,m,p,function(){});m.Ya(d.j);return d.j}),d.Pa.bindTo("latLngPosition",a,"position"),k.bindTo("position",d.Pa,"pixelPosition"))}):(this.Pa=new _.sA,this.Pa.bindTo("latLngPosition",a,"position"),this.Pa.bindTo("center",e,"projectionCenterQ"),this.Pa.bindTo("zoom",e),this.Pa.bindTo("offset",e),this.Pa.bindTo("projection",b),this.Pa.bindTo("focus",b,"position"));this.o=f?a.Fg()?"Ia":"Id":null;this.h=[];var g=new _.tA(["scale"],"visible",
function(m){return null==m||.3<=m});this.Pa&&g.bindTo("scale",this.Pa);var h=a.get("shouldFocus"),k=this.m=uya(b,h);k.set("logAsInternal",a.Fg());k.bindTo("zIndex",a);k.bindTo("layoutPixelBounds",e,"pixelBounds");k.bindTo("disableAutoPan",a);k.bindTo("maxWidth",a);k.bindTo("minWidth",a);k.bindTo("content",a);k.bindTo("pixelOffset",a);k.bindTo("visible",g);this.Pa&&k.bindTo("position",this.Pa,"pixelPosition");this.g=new _.bi(function(){if(b instanceof _.Kf)if(d.i){var m=a.get("position");m&&_.zha(b,
d.i,new _.cg(m),tya(k))}else c.then(function(){return d.g.start()});else(m=k.get("pixelBounds"))?_.L.trigger(e,"pantobounds",m):d.g.start()},150);if(f){var l=null;this.h.push(_.L.Ib(a,"position_changed",function(){var m=a.get("position");!m||a.get("disableAutoPan")||m.equals(l)||(d.g.start(),l=m)}))}else a.get("disableAutoPan")||this.g.start();k.set("open",!0);this.h.push(_.L.addListener(k,"domready",function(){a.trigger("domready")}));this.h.push(_.L.addListener(k,"closeclick",function(){a.close();
a.trigger("closeclick")}));this.o&&_.yg(b,this.o)},vya=function(a,b,c){return b instanceof _.Kf?new cF(a,b,c):new cF(a,b)},wya=function(a){a=a.__gm;return a.IW_AUTO_CLOSER=a.IW_AUTO_CLOSER||new qya};_.Xl.prototype.Lh=_.rk(31,function(a){var b=this.od();return _.hb(b,a)});_.aB.prototype.Lh=_.rk(30,function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if(_.bB(this.h,c)&&this.h[c]==a)return!0}return!1});_.n=XE.prototype;_.n.Rb=function(){return this.g.size};_.n.add=function(a){this.g.set(YE(a),a);this.size=this.g.size};_.n.delete=function(a){a=this.g.remove(YE(a));this.size=this.g.size;return a};_.n.remove=function(a){return this.delete(a)};_.n.clear=function(){this.g.clear();this.size=0};_.n.isEmpty=function(){return 0===this.g.size};_.n.has=function(a){a=YE(a);return this.g.has(a)};_.n.contains=function(a){a=YE(a);return this.g.has(a)};_.n.od=function(){return this.g.od()};
_.n.values=function(){return _.u(this.g,"values").call(this.g)};_.n.clone=function(){return new XE(this)};_.n.equals=function(a){return this.Rb()==nya(a)&&pya(this,a)};_.n.Wg=function(){return this.g.Wg(!1)};XE.prototype[_.u(_.y.Symbol,"iterator")]=function(){return _.u(this,"values").call(this)};_.B($E,_.M);_.n=$E.prototype;_.n.open_changed=function(){sya(this)};_.n.content_changed=function(){sya(this)};_.n.dispose=function(){var a=this;setTimeout(function(){document.activeElement&&document.activeElement!==document.body||(a.l&&a.l!==document.body?_.Pt(a.l,!0)||_.Pt(a.K,!0):_.Pt(a.K,!0))});this.J&&_.L.removeListener(this.J);this.g.parentNode.removeChild(this.g);this.m.stop();this.m.dispose()};
_.n.pixelOffset_changed=function(){var a=this.get("pixelOffset")||new _.sg(0,0);this.o.style.right=_.vl(-a.width);this.o.style.bottom=_.vl(-a.height+11);aF(this)};_.n.layoutPixelBounds_changed=function(){aF(this)};_.n.position_changed=function(){this.get("position")?(bF(this),ZE(this,!!this.get("open"))):ZE(this,!1)};_.n.zIndex_changed=function(){bF(this)};_.n.visible_changed=function(){_.Ht(this.g,this.get("visible"));this.m.start()};
_.n.Zw=function(a){for(var b=!1,c=this.get("content"),d=a.target;!b&&d;)b=d==c,d=d.parentNode;b?_.xf(a):_.zf(a)};_.n.focus=function(){this.l=document.activeElement;if(this.get("disableAutoPan"))_.Pt(this.h,!0);else{var a=_.gla(this.i);if(a.length){a=a[0];var b=this.i.getBoundingClientRect(),c=a.getBoundingClientRect();_.Pt(c.bottom<=b.bottom&&c.right<=b.right?a:this.h,!0)}else _.Pt(this.F.element,!0)}};cF.prototype.close=function(){if(this.l){this.l=!1;for(var a=_.A(this.h),b=a.next();!b.done;b=a.next())_.L.removeListener(b.value);this.h.length=0;this.g.stop();this.g.dispose();this.i&&this.j&&this.i.Ef(this.j);a=this.m;a.unbindAll();a.set("open",!1);a.dispose();this.Pa&&this.Pa.unbindAll()}};_.wf("infowindow",{Ot:function(a){var b=null;_.L.Ib(a,"map_changed",function d(){var e=a.get("map");b&&(b.ap.g.delete(a),b.tx.close(),b=null);if(e){var f=e.__gm;f.get("panes")?(b={tx:vya(a,e,e instanceof _.Kf?f.h.then(function(g){return g.cc}):void 0),ap:wya(e)},rya(b.ap,a)):_.L.addListenerOnce(f,"panes_changed",d)}})}});});
